// GENERATED by tools/gen_options.py from ELK 0.11.0 sources — do not edit.
#![allow(non_camel_case_types)]

use crate::core::data::{parse_enum, LayoutMetaDataRegistry, OptionData, OptionKind, Targets};
#[allow(unused_imports)]
use crate::core::options::*;
use crate::elk_enum;
#[allow(unused_imports)]
use crate::graph::math::{KVector, KVectorChain, Spacing};
use crate::graph::properties::Property;

elk_enum! {
    pub enum CenterEdgeLabelPlacementStrategy {
        MEDIAN_LAYER,
        TAIL_LAYER,
        HEAD_LAYER,
        SPACE_EFFICIENT_LAYER,
        WIDEST_LAYER,
        CENTER_LAYER,
    }
}

elk_enum! {
    pub enum ConstraintCalculationStrategy {
        QUADRATIC,
        SCANLINE,
    }
}

elk_enum! {
    pub enum CrossingMinimizationStrategy {
        LAYER_SWEEP,
        MEDIAN_LAYER_SWEEP,
        INTERACTIVE,
        NONE,
    }
}

elk_enum! {
    pub enum CuttingStrategy {
        ARD,
        MSD,
        MANUAL,
    }
}

elk_enum! {
    pub enum CycleBreakingStrategy {
        GREEDY,
        DEPTH_FIRST,
        INTERACTIVE,
        MODEL_ORDER,
        GREEDY_MODEL_ORDER,
        SCC_CONNECTIVITY,
        SCC_NODE_TYPE,
        DFS_NODE_ORDER,
        BFS_NODE_ORDER,
    }
}

elk_enum! {
    pub enum DirectionCongruency {
        READING_DIRECTION,
        ROTATION,
    }
}

elk_enum! {
    pub enum EdgeConstraint {
        NONE,
        INCOMING_ONLY,
        OUTGOING_ONLY,
    }
}

elk_enum! {
    pub enum EdgeLabelSideSelection {
        ALWAYS_UP,
        ALWAYS_DOWN,
        DIRECTION_UP,
        DIRECTION_DOWN,
        SMART_UP,
        SMART_DOWN,
    }
}

elk_enum! {
    pub enum EdgeStraighteningStrategy {
        NONE,
        IMPROVE_STRAIGHTNESS,
    }
}

elk_enum! {
    pub enum FixedAlignment {
        NONE,
        LEFTUP,
        RIGHTUP,
        LEFTDOWN,
        RIGHTDOWN,
        BALANCED,
    }
}

elk_enum! {
    pub enum GraphCompactionStrategy {
        NONE,
        LEFT,
        RIGHT,
        LEFT_RIGHT_CONSTRAINT_LOCKING,
        LEFT_RIGHT_CONNECTION_LOCKING,
        EDGE_LENGTH,
    }
}

elk_enum! {
    pub enum GraphProperties {
        COMMENTS,
        EXTERNAL_PORTS,
        HYPEREDGES,
        HYPERNODES,
        NON_FREE_PORTS,
        NORTH_SOUTH_PORTS,
        SELF_LOOPS,
        CENTER_LABELS,
        END_LABELS,
        PARTITIONS,
    }
}

elk_enum! {
    pub enum GreedySwitchType {
        ONE_SIDED,
        TWO_SIDED,
        OFF,
    }
}

elk_enum! {
    pub enum GroupOrderStrategy {
        ONLY_WITHIN_GROUP,
        MODEL_ORDER,
        ENFORCED,
    }
}

elk_enum! {
    pub enum InLayerConstraint {
        NONE,
        TOP,
        BOTTOM,
    }
}

elk_enum! {
    pub enum InteractiveReferencePoint {
        CENTER,
        TOP_LEFT,
    }
}

elk_enum! {
    pub enum LayerConstraint {
        NONE,
        FIRST,
        FIRST_SEPARATE,
        LAST,
        LAST_SEPARATE,
    }
}

elk_enum! {
    pub enum LayeringStrategy {
        NETWORK_SIMPLEX,
        LONGEST_PATH,
        LONGEST_PATH_SOURCE,
        COFFMAN_GRAHAM,
        INTERACTIVE,
        STRETCH_WIDTH,
        MIN_WIDTH,
        BF_MODEL_ORDER,
        DF_MODEL_ORDER,
    }
}

elk_enum! {
    pub enum LayerUnzippingStrategy {
        NONE,
        ALTERNATING,
    }
}

elk_enum! {
    pub enum LongEdgeOrderingStrategy {
        DUMMY_NODE_OVER,
        DUMMY_NODE_UNDER,
        EQUAL,
    }
}

impl LongEdgeOrderingStrategy {
    pub fn return_value(self) -> i32 {
        match self {
            LongEdgeOrderingStrategy::DUMMY_NODE_OVER => i32::MAX,
            LongEdgeOrderingStrategy::DUMMY_NODE_UNDER => i32::MIN,
            LongEdgeOrderingStrategy::EQUAL => 0,
        }
    }
}

elk_enum! {
    pub enum NodeFlexibility {
        NONE,
        PORT_POSITION,
        NODE_SIZE_WHERE_SPACE_PERMITS,
        NODE_SIZE,
    }
}

elk_enum! {
    pub enum NodePlacementStrategy {
        SIMPLE,
        INTERACTIVE,
        LINEAR_SEGMENTS,
        BRANDES_KOEPF,
        NETWORK_SIMPLEX,
    }
}

elk_enum! {
    pub enum NodePromotionStrategy {
        NONE,
        NIKOLOV,
        NIKOLOV_PIXEL,
        NIKOLOV_IMPROVED,
        NIKOLOV_IMPROVED_PIXEL,
        DUMMYNODE_PERCENTAGE,
        NODECOUNT_PERCENTAGE,
        NO_BOUNDARY,
        MODEL_ORDER_LEFT_TO_RIGHT,
        MODEL_ORDER_RIGHT_TO_LEFT,
    }
}

elk_enum! {
    pub enum OrderingStrategy {
        NONE,
        NODES_AND_EDGES,
        PREFER_EDGES,
        PREFER_NODES,
    }
}

elk_enum! {
    pub enum PortSortingStrategy {
        INPUT_ORDER,
        PORT_DEGREE,
    }
}

elk_enum! {
    pub enum PortType {
        UNDEFINED,
        INPUT,
        OUTPUT,
    }
}

elk_enum! {
    pub enum SelfLoopDistributionStrategy {
        EQUALLY,
        NORTH,
        NORTH_SOUTH,
    }
}

elk_enum! {
    pub enum SelfLoopOrderingStrategy {
        STACKED,
        REVERSE_STACKED,
        SEQUENCED,
    }
}

elk_enum! {
    pub enum SelfLoopPlacementStrategy {
        EQUALLY_DISTRIBUTED,
        NORTH_STACKED,
        NORTH_SEQUENCE,
    }
}

elk_enum! {
    pub enum SplineRoutingMode {
        CONSERVATIVE,
        CONSERVATIVE_SOFT,
        SLOPPY,
    }
}

elk_enum! {
    pub enum ValidifyStrategy {
        NO,
        GREEDY,
        LOOK_BACK,
    }
}

elk_enum! {
    pub enum WrappingStrategy {
        OFF,
        SINGLE_EDGE,
        MULTI_EDGE,
    }
}

elk_enum! {
    pub enum ComponentOrderingStrategy {
        NONE,
        INSIDE_PORT_SIDE_GROUPS,
        GROUP_MODEL_ORDER,
        MODEL_ORDER,
    }
}

pub static DIRECTION_CONGRUENCY: Property<DirectionCongruency> = Property::with_default("org.eclipse.elk.layered.directionCongruency", || DirectionCongruency::READING_DIRECTION);
pub static FEEDBACK_EDGES: Property<bool> = Property::with_default("org.eclipse.elk.layered.feedbackEdges", || false);
pub static INTERACTIVE_REFERENCE_POINT: Property<InteractiveReferencePoint> = Property::with_default("org.eclipse.elk.layered.interactiveReferencePoint", || InteractiveReferencePoint::CENTER);
pub static MERGE_EDGES: Property<bool> = Property::with_default("org.eclipse.elk.layered.mergeEdges", || false);
pub static MERGE_HIERARCHY_EDGES: Property<bool> = Property::with_default("org.eclipse.elk.layered.mergeHierarchyEdges", || true);
pub static ALLOW_NON_FLOW_PORTS_TO_SWITCH_SIDES: Property<bool> = Property::with_default("org.eclipse.elk.layered.allowNonFlowPortsToSwitchSides", || false);
pub static PORT_SORTING_STRATEGY: Property<PortSortingStrategy> = Property::with_default("org.eclipse.elk.layered.portSortingStrategy", || PortSortingStrategy::INPUT_ORDER);
pub static THOROUGHNESS: Property<i32> = Property::with_default("org.eclipse.elk.layered.thoroughness", || 7);
pub static UNNECESSARY_BENDPOINTS: Property<bool> = Property::with_default("org.eclipse.elk.layered.unnecessaryBendpoints", || false);
pub static GENERATE_POSITION_AND_LAYER_IDS: Property<bool> = Property::with_default("org.eclipse.elk.layered.generatePositionAndLayerIds", || false);
pub static CYCLE_BREAKING_STRATEGY: Property<CycleBreakingStrategy> = Property::with_default("org.eclipse.elk.layered.cycleBreaking.strategy", || CycleBreakingStrategy::GREEDY);
pub static LAYERING_STRATEGY: Property<LayeringStrategy> = Property::with_default("org.eclipse.elk.layered.layering.strategy", || LayeringStrategy::NETWORK_SIMPLEX);
pub static LAYERING_LAYER_CONSTRAINT: Property<LayerConstraint> = Property::with_default("org.eclipse.elk.layered.layering.layerConstraint", || LayerConstraint::NONE);
pub static LAYERING_LAYER_CHOICE_CONSTRAINT: Property<i32> = Property::new("org.eclipse.elk.layered.layering.layerChoiceConstraint");
pub static LAYERING_LAYER_ID: Property<i32> = Property::with_default("org.eclipse.elk.layered.layering.layerId", || -1);
pub static LAYERING_MIN_WIDTH_UPPER_BOUND_ON_WIDTH: Property<i32> = Property::with_default("org.eclipse.elk.layered.layering.minWidth.upperBoundOnWidth", || 4);
pub static LAYERING_MIN_WIDTH_UPPER_LAYER_ESTIMATION_SCALING_FACTOR: Property<i32> = Property::with_default("org.eclipse.elk.layered.layering.minWidth.upperLayerEstimationScalingFactor", || 2);
pub static LAYERING_NODE_PROMOTION_STRATEGY: Property<NodePromotionStrategy> = Property::with_default("org.eclipse.elk.layered.layering.nodePromotion.strategy", || NodePromotionStrategy::NONE);
pub static LAYERING_NODE_PROMOTION_MAX_ITERATIONS: Property<i32> = Property::with_default("org.eclipse.elk.layered.layering.nodePromotion.maxIterations", || 0);
pub static LAYERING_COFFMAN_GRAHAM_LAYER_BOUND: Property<i32> = Property::with_default("org.eclipse.elk.layered.layering.coffmanGraham.layerBound", || i32::MAX);
pub static CROSSING_MINIMIZATION_STRATEGY: Property<CrossingMinimizationStrategy> = Property::with_default("org.eclipse.elk.layered.crossingMinimization.strategy", || CrossingMinimizationStrategy::LAYER_SWEEP);
pub static CROSSING_MINIMIZATION_FORCE_NODE_MODEL_ORDER: Property<bool> = Property::with_default("org.eclipse.elk.layered.crossingMinimization.forceNodeModelOrder", || false);
pub static CROSSING_MINIMIZATION_HIERARCHICAL_SWEEPINESS: Property<f64> = Property::with_default("org.eclipse.elk.layered.crossingMinimization.hierarchicalSweepiness", || 0.1);
pub static CROSSING_MINIMIZATION_SEMI_INTERACTIVE: Property<bool> = Property::with_default("org.eclipse.elk.layered.crossingMinimization.semiInteractive", || false);
pub static CROSSING_MINIMIZATION_IN_LAYER_PRED_OF: Property<String> = Property::new("org.eclipse.elk.layered.crossingMinimization.inLayerPredOf");
pub static CROSSING_MINIMIZATION_IN_LAYER_SUCC_OF: Property<String> = Property::new("org.eclipse.elk.layered.crossingMinimization.inLayerSuccOf");
pub static CROSSING_MINIMIZATION_POSITION_CHOICE_CONSTRAINT: Property<i32> = Property::new("org.eclipse.elk.layered.crossingMinimization.positionChoiceConstraint");
pub static CROSSING_MINIMIZATION_POSITION_ID: Property<i32> = Property::with_default("org.eclipse.elk.layered.crossingMinimization.positionId", || -1);
pub static CROSSING_MINIMIZATION_GREEDY_SWITCH_ACTIVATION_THRESHOLD: Property<i32> = Property::with_default("org.eclipse.elk.layered.crossingMinimization.greedySwitch.activationThreshold", || 40);
pub static CROSSING_MINIMIZATION_GREEDY_SWITCH_TYPE: Property<GreedySwitchType> = Property::with_default("org.eclipse.elk.layered.crossingMinimization.greedySwitch.type", || GreedySwitchType::TWO_SIDED);
pub static CROSSING_MINIMIZATION_GREEDY_SWITCH_HIERARCHICAL_TYPE: Property<GreedySwitchType> = Property::with_default("org.eclipse.elk.layered.crossingMinimization.greedySwitchHierarchical.type", || GreedySwitchType::OFF);
pub static NODE_PLACEMENT_STRATEGY: Property<NodePlacementStrategy> = Property::with_default("org.eclipse.elk.layered.nodePlacement.strategy", || NodePlacementStrategy::BRANDES_KOEPF);
pub static NODE_PLACEMENT_FAVOR_STRAIGHT_EDGES: Property<bool> = Property::new("org.eclipse.elk.layered.nodePlacement.favorStraightEdges");
pub static NODE_PLACEMENT_BK_EDGE_STRAIGHTENING: Property<EdgeStraighteningStrategy> = Property::with_default("org.eclipse.elk.layered.nodePlacement.bk.edgeStraightening", || EdgeStraighteningStrategy::IMPROVE_STRAIGHTNESS);
pub static NODE_PLACEMENT_BK_FIXED_ALIGNMENT: Property<FixedAlignment> = Property::with_default("org.eclipse.elk.layered.nodePlacement.bk.fixedAlignment", || FixedAlignment::NONE);
pub static NODE_PLACEMENT_LINEAR_SEGMENTS_DEFLECTION_DAMPENING: Property<f64> = Property::with_default("org.eclipse.elk.layered.nodePlacement.linearSegments.deflectionDampening", || 0.3);
pub static NODE_PLACEMENT_NETWORK_SIMPLEX_NODE_FLEXIBILITY: Property<NodeFlexibility> = Property::new("org.eclipse.elk.layered.nodePlacement.networkSimplex.nodeFlexibility");
pub static NODE_PLACEMENT_NETWORK_SIMPLEX_NODE_FLEXIBILITY_DEFAULT: Property<NodeFlexibility> = Property::with_default("org.eclipse.elk.layered.nodePlacement.networkSimplex.nodeFlexibility.default", || NodeFlexibility::NONE);
pub static EDGE_ROUTING_SELF_LOOP_DISTRIBUTION: Property<SelfLoopDistributionStrategy> = Property::with_default("org.eclipse.elk.layered.edgeRouting.selfLoopDistribution", || SelfLoopDistributionStrategy::NORTH);
pub static EDGE_ROUTING_SELF_LOOP_ORDERING: Property<SelfLoopOrderingStrategy> = Property::with_default("org.eclipse.elk.layered.edgeRouting.selfLoopOrdering", || SelfLoopOrderingStrategy::STACKED);
pub static EDGE_ROUTING_SPLINES_MODE: Property<SplineRoutingMode> = Property::with_default("org.eclipse.elk.layered.edgeRouting.splines.mode", || SplineRoutingMode::SLOPPY);
pub static EDGE_ROUTING_SPLINES_SLOPPY_LAYER_SPACING_FACTOR: Property<f64> = Property::with_default("org.eclipse.elk.layered.edgeRouting.splines.sloppy.layerSpacingFactor", || 0.2);
pub static EDGE_ROUTING_POLYLINE_SLOPED_EDGE_ZONE_WIDTH: Property<f64> = Property::with_default("org.eclipse.elk.layered.edgeRouting.polyline.slopedEdgeZoneWidth", || 2.0);
pub static SPACING_BASE_VALUE: Property<f64> = Property::new("org.eclipse.elk.layered.spacing.baseValue");
pub static SPACING_EDGE_NODE_BETWEEN_LAYERS: Property<f64> = Property::with_default("org.eclipse.elk.layered.spacing.edgeNodeBetweenLayers", || 10.0);
pub static SPACING_EDGE_EDGE_BETWEEN_LAYERS: Property<f64> = Property::with_default("org.eclipse.elk.layered.spacing.edgeEdgeBetweenLayers", || 10.0);
pub static SPACING_NODE_NODE_BETWEEN_LAYERS: Property<f64> = Property::with_default("org.eclipse.elk.layered.spacing.nodeNodeBetweenLayers", || 20.0);
pub static PRIORITY_DIRECTION: Property<i32> = Property::with_default("org.eclipse.elk.layered.priority.direction", || 0);
pub static PRIORITY_SHORTNESS: Property<i32> = Property::with_default("org.eclipse.elk.layered.priority.shortness", || 0);
pub static PRIORITY_STRAIGHTNESS: Property<i32> = Property::with_default("org.eclipse.elk.layered.priority.straightness", || 0);
pub static COMPACTION_CONNECTED_COMPONENTS: Property<bool> = Property::with_default("org.eclipse.elk.layered.compaction.connectedComponents", || false);
pub static COMPACTION_POST_COMPACTION_STRATEGY: Property<GraphCompactionStrategy> = Property::with_default("org.eclipse.elk.layered.compaction.postCompaction.strategy", || GraphCompactionStrategy::NONE);
pub static COMPACTION_POST_COMPACTION_CONSTRAINTS: Property<ConstraintCalculationStrategy> = Property::with_default("org.eclipse.elk.layered.compaction.postCompaction.constraints", || ConstraintCalculationStrategy::SCANLINE);
pub static HIGH_DEGREE_NODES_TREATMENT: Property<bool> = Property::with_default("org.eclipse.elk.layered.highDegreeNodes.treatment", || false);
pub static HIGH_DEGREE_NODES_THRESHOLD: Property<i32> = Property::with_default("org.eclipse.elk.layered.highDegreeNodes.threshold", || 16);
pub static HIGH_DEGREE_NODES_TREE_HEIGHT: Property<i32> = Property::with_default("org.eclipse.elk.layered.highDegreeNodes.treeHeight", || 5);
pub static WRAPPING_STRATEGY: Property<WrappingStrategy> = Property::with_default("org.eclipse.elk.layered.wrapping.strategy", || WrappingStrategy::OFF);
pub static WRAPPING_ADDITIONAL_EDGE_SPACING: Property<f64> = Property::with_default("org.eclipse.elk.layered.wrapping.additionalEdgeSpacing", || 10.0);
pub static WRAPPING_CORRECTION_FACTOR: Property<f64> = Property::with_default("org.eclipse.elk.layered.wrapping.correctionFactor", || 1.0);
pub static WRAPPING_CUTTING_STRATEGY: Property<CuttingStrategy> = Property::with_default("org.eclipse.elk.layered.wrapping.cutting.strategy", || CuttingStrategy::MSD);
pub static WRAPPING_CUTTING_CUTS: Property<Vec<i32>> = Property::new("org.eclipse.elk.layered.wrapping.cutting.cuts");
pub static WRAPPING_CUTTING_MSD_FREEDOM: Property<i32> = Property::with_default("org.eclipse.elk.layered.wrapping.cutting.msd.freedom", || 1);
pub static WRAPPING_VALIDIFY_STRATEGY: Property<ValidifyStrategy> = Property::with_default("org.eclipse.elk.layered.wrapping.validify.strategy", || ValidifyStrategy::GREEDY);
pub static WRAPPING_VALIDIFY_FORBIDDEN_INDICES: Property<Vec<i32>> = Property::new("org.eclipse.elk.layered.wrapping.validify.forbiddenIndices");
pub static WRAPPING_MULTI_EDGE_IMPROVE_CUTS: Property<bool> = Property::with_default("org.eclipse.elk.layered.wrapping.multiEdge.improveCuts", || true);
pub static WRAPPING_MULTI_EDGE_DISTANCE_PENALTY: Property<f64> = Property::with_default("org.eclipse.elk.layered.wrapping.multiEdge.distancePenalty", || 2.0);
pub static WRAPPING_MULTI_EDGE_IMPROVE_WRAPPED_EDGES: Property<bool> = Property::with_default("org.eclipse.elk.layered.wrapping.multiEdge.improveWrappedEdges", || true);
pub static LAYER_UNZIPPING_STRATEGY: Property<LayerUnzippingStrategy> = Property::with_default("org.eclipse.elk.layered.layerUnzipping.strategy", || LayerUnzippingStrategy::NONE);
pub static LAYER_UNZIPPING_MINIMIZE_EDGE_LENGTH: Property<bool> = Property::with_default("org.eclipse.elk.layered.layerUnzipping.minimizeEdgeLength", || false);
pub static LAYER_UNZIPPING_LAYER_SPLIT: Property<i32> = Property::with_default("org.eclipse.elk.layered.layerUnzipping.layerSplit", || 2);
pub static LAYER_UNZIPPING_RESET_ON_LONG_EDGES: Property<bool> = Property::with_default("org.eclipse.elk.layered.layerUnzipping.resetOnLongEdges", || true);
pub static EDGE_LABELS_SIDE_SELECTION: Property<EdgeLabelSideSelection> = Property::with_default("org.eclipse.elk.layered.edgeLabels.sideSelection", || EdgeLabelSideSelection::SMART_DOWN);
pub static EDGE_LABELS_CENTER_LABEL_PLACEMENT_STRATEGY: Property<CenterEdgeLabelPlacementStrategy> = Property::with_default("org.eclipse.elk.layered.edgeLabels.centerLabelPlacementStrategy", || CenterEdgeLabelPlacementStrategy::MEDIAN_LAYER);
pub static CONSIDER_MODEL_ORDER_STRATEGY: Property<OrderingStrategy> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.strategy", || OrderingStrategy::NONE);
pub static CONSIDER_MODEL_ORDER_PORT_MODEL_ORDER: Property<bool> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.portModelOrder", || false);
pub static CONSIDER_MODEL_ORDER_NO_MODEL_ORDER: Property<bool> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.noModelOrder", || false);
pub static CONSIDER_MODEL_ORDER_COMPONENTS: Property<ComponentOrderingStrategy> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.components", || ComponentOrderingStrategy::NONE);
pub static CONSIDER_MODEL_ORDER_LONG_EDGE_STRATEGY: Property<LongEdgeOrderingStrategy> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.longEdgeStrategy", || LongEdgeOrderingStrategy::DUMMY_NODE_OVER);
pub static CONSIDER_MODEL_ORDER_CROSSING_COUNTER_NODE_INFLUENCE: Property<f64> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.crossingCounterNodeInfluence", || 0.0);
pub static CONSIDER_MODEL_ORDER_CROSSING_COUNTER_PORT_INFLUENCE: Property<f64> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.crossingCounterPortInfluence", || 0.0);
pub static CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CYCLE_BREAKING_ID: Property<i32> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cycleBreakingId", || 0);
pub static CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CROSSING_MINIMIZATION_ID: Property<i32> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.groupModelOrder.crossingMinimizationId", || 0);
pub static CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_COMPONENT_GROUP_ID: Property<i32> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.groupModelOrder.componentGroupId", || 0);
pub static CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CB_GROUP_ORDER_STRATEGY: Property<GroupOrderStrategy> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbGroupOrderStrategy", || GroupOrderStrategy::ONLY_WITHIN_GROUP);
pub static CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CB_PREFERRED_SOURCE_ID: Property<i32> = Property::new("org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbPreferredSourceId");
pub static CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CB_PREFERRED_TARGET_ID: Property<i32> = Property::new("org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbPreferredTargetId");
pub static CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CM_GROUP_ORDER_STRATEGY: Property<GroupOrderStrategy> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cmGroupOrderStrategy", || GroupOrderStrategy::ONLY_WITHIN_GROUP);
pub static CONSIDER_MODEL_ORDER_GROUP_MODEL_ORDER_CM_ENFORCED_GROUP_ORDERS: Property<Vec<i32>> = Property::with_default("org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cmEnforcedGroupOrders", || vec![1, 2, 6, 7, 10, 11]);


pub static PRIORITY: Property<i32> = Property::with_default("org.eclipse.elk.priority", || 0);
pub static TOPDOWN_NODE_TYPE: Property<TopdownNodeTypes> = Property::with_default("org.eclipse.elk.topdown.nodeType", || TopdownNodeTypes::HIERARCHICAL_NODE);
pub static PADDING: Property<ElkPadding> = Property::with_default("org.eclipse.elk.padding", || Spacing::uniform(12.0f64));
pub static EDGE_ROUTING: Property<EdgeRouting> = Property::with_default("org.eclipse.elk.edgeRouting", || EdgeRouting::ORTHOGONAL);
pub static PORT_BORDER_OFFSET: Property<f64> = Property::with_default("org.eclipse.elk.port.borderOffset", || 0.0);
pub static RANDOM_SEED: Property<i32> = Property::with_default("org.eclipse.elk.randomSeed", || 1);
pub static ASPECT_RATIO: Property<f64> = Property::with_default("org.eclipse.elk.aspectRatio", || 1.6);
pub static SEPARATE_CONNECTED_COMPONENTS: Property<bool> = Property::with_default("org.eclipse.elk.separateConnectedComponents", || true);
pub static DIRECTION: Property<Direction> = Property::with_default("org.eclipse.elk.direction", || Direction::UNDEFINED);
pub static PORT_ALIGNMENT_DEFAULT: Property<PortAlignment> = Property::with_default("org.eclipse.elk.portAlignment.default", || PortAlignment::JUSTIFIED);

pub use crate::core::options::SPACING_COMMENT_COMMENT as SPACING_COMMENT_COMMENT;
pub use crate::core::options::SPACING_COMMENT_NODE as SPACING_COMMENT_NODE;
pub use crate::core::options::SPACING_COMPONENT_COMPONENT as SPACING_COMPONENT_COMPONENT;
pub use crate::core::options::SPACING_EDGE_EDGE as SPACING_EDGE_EDGE;
pub use crate::core::options::SPACING_EDGE_LABEL as SPACING_EDGE_LABEL;
pub use crate::core::options::SPACING_EDGE_NODE as SPACING_EDGE_NODE;
pub use crate::core::options::SPACING_LABEL_LABEL as SPACING_LABEL_LABEL;
pub use crate::core::options::SPACING_LABEL_PORT_HORIZONTAL as SPACING_LABEL_PORT_HORIZONTAL;
pub use crate::core::options::SPACING_LABEL_PORT_VERTICAL as SPACING_LABEL_PORT_VERTICAL;
pub use crate::core::options::SPACING_LABEL_NODE as SPACING_LABEL_NODE;
pub use crate::core::options::SPACING_NODE_NODE as SPACING_NODE_NODE;
pub use crate::core::options::SPACING_NODE_SELF_LOOP as SPACING_NODE_SELF_LOOP;
pub use crate::core::options::SPACING_PORT_PORT as SPACING_PORT_PORT;
pub use crate::core::options::SPACING_INDIVIDUAL as SPACING_INDIVIDUAL;
pub use crate::core::options::TOPDOWN_LAYOUT as TOPDOWN_LAYOUT;
pub use crate::core::options::TOPDOWN_SCALE_FACTOR as TOPDOWN_SCALE_FACTOR;
pub use crate::core::options::TOPDOWN_HIERARCHICAL_NODE_WIDTH as TOPDOWN_HIERARCHICAL_NODE_WIDTH;
pub use crate::core::options::TOPDOWN_HIERARCHICAL_NODE_ASPECT_RATIO as TOPDOWN_HIERARCHICAL_NODE_ASPECT_RATIO;
pub use crate::core::options::NO_LAYOUT as NO_LAYOUT;
pub use crate::core::options::PORT_CONSTRAINTS as PORT_CONSTRAINTS;
pub use crate::core::options::PORT_SIDE as PORT_SIDE;
pub use crate::core::options::DEBUG_MODE as DEBUG_MODE;
pub use crate::core::options::ALIGNMENT as ALIGNMENT;
pub use crate::core::options::HIERARCHY_HANDLING as HIERARCHY_HANDLING;
pub use crate::core::options::INSIDE_SELF_LOOPS_ACTIVATE as INSIDE_SELF_LOOPS_ACTIVATE;
pub use crate::core::options::INSIDE_SELF_LOOPS_YO as INSIDE_SELF_LOOPS_YO;
pub use crate::core::options::NODE_SIZE_CONSTRAINTS as NODE_SIZE_CONSTRAINTS;
pub use crate::core::options::NODE_SIZE_OPTIONS as NODE_SIZE_OPTIONS;
pub use crate::core::options::NODE_SIZE_FIXED_GRAPH_SIZE as NODE_SIZE_FIXED_GRAPH_SIZE;
pub use crate::core::options::NODE_LABELS_PLACEMENT as NODE_LABELS_PLACEMENT;
pub use crate::core::options::NODE_LABELS_PADDING as NODE_LABELS_PADDING;
pub use crate::core::options::PORT_LABELS_PLACEMENT as PORT_LABELS_PLACEMENT;
pub use crate::core::options::PORT_LABELS_NEXT_TO_PORT_IF_POSSIBLE as PORT_LABELS_NEXT_TO_PORT_IF_POSSIBLE;
pub use crate::core::options::PORT_LABELS_TREAT_AS_GROUP as PORT_LABELS_TREAT_AS_GROUP;
pub use crate::core::options::PORT_ALIGNMENT_NORTH as PORT_ALIGNMENT_NORTH;
pub use crate::core::options::PORT_ALIGNMENT_SOUTH as PORT_ALIGNMENT_SOUTH;
pub use crate::core::options::PORT_ALIGNMENT_WEST as PORT_ALIGNMENT_WEST;
pub use crate::core::options::PORT_ALIGNMENT_EAST as PORT_ALIGNMENT_EAST;
pub use crate::core::options::CONTENT_ALIGNMENT as CONTENT_ALIGNMENT;
pub use crate::core::options::NODE_SIZE_MINIMUM as NODE_SIZE_MINIMUM;
pub use crate::core::options::JUNCTION_POINTS as JUNCTION_POINTS;
pub use crate::core::options::EDGE_THICKNESS as EDGE_THICKNESS;
pub use crate::core::options::EDGE_LABELS_PLACEMENT as EDGE_LABELS_PLACEMENT;
pub use crate::core::options::EDGE_LABELS_INLINE as EDGE_LABELS_INLINE;
pub use crate::core::options::PORT_INDEX as PORT_INDEX;
pub use crate::core::options::COMMENT_BOX as COMMENT_BOX;
pub use crate::core::options::HYPERNODE as HYPERNODE;
pub use crate::core::options::PORT_ANCHOR as PORT_ANCHOR;
pub use crate::core::options::PARTITIONING_ACTIVATE as PARTITIONING_ACTIVATE;
pub use crate::core::options::PARTITIONING_PARTITION as PARTITIONING_PARTITION;
pub use crate::core::options::POSITION as POSITION;
pub use crate::core::options::MARGINS as MARGINS;
pub use crate::core::options::SPACING_PORTS_SURROUNDING as SPACING_PORTS_SURROUNDING;
pub use crate::core::options::INTERACTIVE_LAYOUT as INTERACTIVE_LAYOUT;

pub fn register_layered_options(reg: &mut LayoutMetaDataRegistry) {
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.directionCongruency", group: "", kind: OptionKind::Enum(parse_enum::<DirectionCongruency>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.feedbackEdges", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.interactiveReferencePoint", group: "", kind: OptionKind::Enum(parse_enum::<InteractiveReferencePoint>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.mergeEdges", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.mergeHierarchyEdges", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.allowNonFlowPortsToSwitchSides", group: "", kind: OptionKind::Bool, targets: Targets::PORTS, legacy_ids: &["org.eclipse.elk.layered.northOrSouthPort"] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.portSortingStrategy", group: "", kind: OptionKind::Enum(parse_enum::<PortSortingStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.thoroughness", group: "", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.unnecessaryBendpoints", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.generatePositionAndLayerIds", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.cycleBreaking.strategy", group: "cycleBreaking", kind: OptionKind::Enum(parse_enum::<CycleBreakingStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layering.strategy", group: "layering", kind: OptionKind::Enum(parse_enum::<LayeringStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layering.layerConstraint", group: "layering", kind: OptionKind::Enum(parse_enum::<LayerConstraint>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layering.layerChoiceConstraint", group: "layering", kind: OptionKind::Int, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layering.layerId", group: "layering", kind: OptionKind::Int, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layering.minWidth.upperBoundOnWidth", group: "layering.minWidth", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layering.minWidth.upperLayerEstimationScalingFactor", group: "layering.minWidth", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layering.nodePromotion.strategy", group: "layering.nodePromotion", kind: OptionKind::Enum(parse_enum::<NodePromotionStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layering.nodePromotion.maxIterations", group: "layering.nodePromotion", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layering.coffmanGraham.layerBound", group: "layering.coffmanGraham", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.crossingMinimization.strategy", group: "crossingMinimization", kind: OptionKind::Enum(parse_enum::<CrossingMinimizationStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.crossingMinimization.forceNodeModelOrder", group: "crossingMinimization", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.crossingMinimization.hierarchicalSweepiness", group: "crossingMinimization", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.crossingMinimization.semiInteractive", group: "crossingMinimization", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.crossingMinimization.inLayerPredOf", group: "crossingMinimization", kind: OptionKind::Str, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.crossingMinimization.inLayerSuccOf", group: "crossingMinimization", kind: OptionKind::Str, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.crossingMinimization.positionChoiceConstraint", group: "crossingMinimization", kind: OptionKind::Int, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.crossingMinimization.positionId", group: "crossingMinimization", kind: OptionKind::Int, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.crossingMinimization.greedySwitch.activationThreshold", group: "crossingMinimization.greedySwitch", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.crossingMinimization.greedySwitch.type", group: "crossingMinimization.greedySwitch", kind: OptionKind::Enum(parse_enum::<GreedySwitchType>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.crossingMinimization.greedySwitchHierarchical.type", group: "crossingMinimization.greedySwitchHierarchical", kind: OptionKind::Enum(parse_enum::<GreedySwitchType>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.nodePlacement.strategy", group: "nodePlacement", kind: OptionKind::Enum(parse_enum::<NodePlacementStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.nodePlacement.favorStraightEdges", group: "nodePlacement", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.nodePlacement.bk.edgeStraightening", group: "nodePlacement.bk", kind: OptionKind::Enum(parse_enum::<EdgeStraighteningStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.nodePlacement.bk.fixedAlignment", group: "nodePlacement.bk", kind: OptionKind::Enum(parse_enum::<FixedAlignment>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.nodePlacement.linearSegments.deflectionDampening", group: "nodePlacement.linearSegments", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.nodePlacement.networkSimplex.nodeFlexibility", group: "nodePlacement.networkSimplex", kind: OptionKind::Enum(parse_enum::<NodeFlexibility>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.nodePlacement.networkSimplex.nodeFlexibility.default", group: "nodePlacement.networkSimplex.nodeFlexibility", kind: OptionKind::Enum(parse_enum::<NodeFlexibility>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.edgeRouting.selfLoopDistribution", group: "edgeRouting", kind: OptionKind::Enum(parse_enum::<SelfLoopDistributionStrategy>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.edgeRouting.selfLoopOrdering", group: "edgeRouting", kind: OptionKind::Enum(parse_enum::<SelfLoopOrderingStrategy>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.edgeRouting.splines.mode", group: "edgeRouting.splines", kind: OptionKind::Enum(parse_enum::<SplineRoutingMode>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.edgeRouting.splines.sloppy.layerSpacingFactor", group: "edgeRouting.splines.sloppy", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.edgeRouting.polyline.slopedEdgeZoneWidth", group: "edgeRouting.polyline", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.spacing.baseValue", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.spacing.edgeNodeBetweenLayers", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.spacing.edgeEdgeBetweenLayers", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.spacing.nodeNodeBetweenLayers", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.priority.direction", group: "priority", kind: OptionKind::Int, targets: Targets::EDGES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.priority.shortness", group: "priority", kind: OptionKind::Int, targets: Targets::EDGES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.priority.straightness", group: "priority", kind: OptionKind::Int, targets: Targets::EDGES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.compaction.connectedComponents", group: "compaction", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.compaction.postCompaction.strategy", group: "compaction.postCompaction", kind: OptionKind::Enum(parse_enum::<GraphCompactionStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.compaction.postCompaction.constraints", group: "compaction.postCompaction", kind: OptionKind::Enum(parse_enum::<ConstraintCalculationStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.highDegreeNodes.treatment", group: "highDegreeNodes", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.highDegreeNodes.threshold", group: "highDegreeNodes", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.highDegreeNodes.treeHeight", group: "highDegreeNodes", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.wrapping.strategy", group: "wrapping", kind: OptionKind::Enum(parse_enum::<WrappingStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.wrapping.additionalEdgeSpacing", group: "wrapping", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.wrapping.correctionFactor", group: "wrapping", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.wrapping.cutting.strategy", group: "wrapping.cutting", kind: OptionKind::Enum(parse_enum::<CuttingStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.wrapping.cutting.cuts", group: "wrapping.cutting", kind: OptionKind::Unparseable, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.wrapping.cutting.msd.freedom", group: "wrapping.cutting.msd", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.wrapping.validify.strategy", group: "wrapping.validify", kind: OptionKind::Enum(parse_enum::<ValidifyStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.wrapping.validify.forbiddenIndices", group: "wrapping.validify", kind: OptionKind::Unparseable, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.wrapping.multiEdge.improveCuts", group: "wrapping.multiEdge", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.wrapping.multiEdge.distancePenalty", group: "wrapping.multiEdge", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.wrapping.multiEdge.improveWrappedEdges", group: "wrapping.multiEdge", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layerUnzipping.strategy", group: "layerUnzipping", kind: OptionKind::Enum(parse_enum::<LayerUnzippingStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layerUnzipping.minimizeEdgeLength", group: "layerUnzipping", kind: OptionKind::Bool, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layerUnzipping.layerSplit", group: "layerUnzipping", kind: OptionKind::Int, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.layerUnzipping.resetOnLongEdges", group: "layerUnzipping", kind: OptionKind::Bool, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.edgeLabels.sideSelection", group: "edgeLabels", kind: OptionKind::Enum(parse_enum::<EdgeLabelSideSelection>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.edgeLabels.centerLabelPlacementStrategy", group: "edgeLabels", kind: OptionKind::Enum(parse_enum::<CenterEdgeLabelPlacementStrategy>), targets: Targets::PARENTS | Targets::LABELS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.strategy", group: "considerModelOrder", kind: OptionKind::Enum(parse_enum::<OrderingStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.portModelOrder", group: "considerModelOrder", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.noModelOrder", group: "considerModelOrder", kind: OptionKind::Bool, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.components", group: "considerModelOrder", kind: OptionKind::Enum(parse_enum::<ComponentOrderingStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.longEdgeStrategy", group: "considerModelOrder", kind: OptionKind::Enum(parse_enum::<LongEdgeOrderingStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.crossingCounterNodeInfluence", group: "considerModelOrder", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.crossingCounterPortInfluence", group: "considerModelOrder", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cycleBreakingId", group: "considerModelOrder.groupModelOrder", kind: OptionKind::Int, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.crossingMinimizationId", group: "considerModelOrder.groupModelOrder", kind: OptionKind::Int, targets: Targets::NODES | Targets::EDGES | Targets::PORTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.componentGroupId", group: "considerModelOrder.groupModelOrder", kind: OptionKind::Int, targets: Targets::NODES | Targets::EDGES | Targets::PORTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbGroupOrderStrategy", group: "considerModelOrder.groupModelOrder", kind: OptionKind::Enum(parse_enum::<GroupOrderStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbPreferredSourceId", group: "considerModelOrder.groupModelOrder", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cbPreferredTargetId", group: "considerModelOrder.groupModelOrder", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cmGroupOrderStrategy", group: "considerModelOrder.groupModelOrder", kind: OptionKind::Enum(parse_enum::<GroupOrderStrategy>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layered.considerModelOrder.groupModelOrder.cmEnforcedGroupOrders", group: "considerModelOrder.groupModelOrder", kind: OptionKind::Unparseable, targets: Targets::PARENTS, legacy_ids: &[] });
}

