//! Golden tests: every case in goldens/cases/ must produce output identical
//! to the Java oracle's (goldens/expected/, regenerated by
//! tools/gen_goldens.sh).

use serde_json::Value;

fn compare(a: &Value, b: &Value, path: &str, diffs: &mut Vec<String>) {
    match (a, b) {
        (Value::Object(ma), Value::Object(mb)) => {
            for (k, va) in ma {
                match mb.get(k) {
                    None => diffs.push(format!("{path}.{k}: missing in rust output ({va})")),
                    Some(vb) => compare(va, vb, &format!("{path}.{k}"), diffs),
                }
            }
            for k in mb.keys() {
                if !ma.contains_key(k) {
                    diffs.push(format!("{path}.{k}: extra in rust output ({})", mb[k]));
                }
            }
        }
        (Value::Array(aa), Value::Array(ab)) => {
            if aa.len() != ab.len() {
                diffs.push(format!("{path}: array length {} != {}", aa.len(), ab.len()));
            }
            for (i, (va, vb)) in aa.iter().zip(ab.iter()).enumerate() {
                compare(va, vb, &format!("{path}[{i}]"), diffs);
            }
        }
        (Value::Number(na), Value::Number(nb)) => {
            if na.as_f64() != nb.as_f64() {
                diffs.push(format!("{path}: {na} != {nb}"));
            }
        }
        _ => {
            if a != b {
                diffs.push(format!("{path}: {a} != {b}"));
            }
        }
    }
}

#[test]
fn golden_cases_match_oracle() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(".");
    let cases_dir = root.join("goldens/cases");
    let expected_dir = root.join("goldens/expected");

    // The golden corpus is a development artifact excluded from the published
    // crate; skip when it isn't present (e.g. when testing a packaged build).
    if !cases_dir.is_dir() {
        eprintln!("goldens/cases not present — skipping golden suite");
        return;
    }

    let elk = elkrs::create_elk();
    let mut failures = Vec::new();
    let mut total = 0;

    let mut entries: Vec<_> = std::fs::read_dir(&cases_dir)
        .expect("goldens/cases missing")
        .map(|e| e.unwrap().path())
        .filter(|p| p.extension().is_some_and(|e| e == "json"))
        .collect();
    entries.sort();

    for case_path in entries {
        let name = case_path.file_stem().unwrap().to_string_lossy().to_string();
        let expected_path = expected_dir.join(format!("{name}.json"));
        if !expected_path.exists() {
            continue; // golden not generated (e.g. unsupported algorithm)
        }
        total += 1;
        let input = std::fs::read_to_string(&case_path).unwrap();
        let expected: Value =
            serde_json::from_str(&std::fs::read_to_string(&expected_path).unwrap()).unwrap();
        match elk.layout_json(&input) {
            Ok(actual) => {
                let mut diffs = Vec::new();
                compare(&expected, &actual, "$", &mut diffs);
                if !diffs.is_empty() {
                    failures.push(format!(
                        "{name}: {} diffs\n  {}",
                        diffs.len(),
                        diffs[..diffs.len().min(10)].join("\n  ")
                    ));
                }
            }
            Err(e) => failures.push(format!("{name}: layout error: {e}")),
        }
    }

    assert!(total > 0, "no golden cases found");
    assert!(
        failures.is_empty(),
        "{} of {} golden cases failed:\n{}",
        failures.len(),
        total,
        failures.join("\n")
    );
    println!("all {total} golden cases identical");
}
