// GENERATED by tools/gen_options.py from ELK 0.11.0 sources — do not edit.
#![allow(non_camel_case_types)]

use crate::elk_enum;
use crate::graph::math::{KVector, KVectorChain, Spacing};
pub use crate::graph::math::{ElkMargin, ElkPadding};
use crate::graph::properties::{EnumSet, Property};
use crate::core::data::{parse_enum, parse_enumset, parse_individual_spacings, parse_kvector, parse_kvectorchain, parse_margin, parse_padding, LayoutMetaDataRegistry, OptionData, OptionKind, Targets};
use crate::core::util::IndividualSpacings;

elk_enum! {
    pub enum Alignment {
        AUTOMATIC,
        LEFT,
        RIGHT,
        TOP,
        BOTTOM,
        CENTER,
    }
}

elk_enum! {
    pub enum ContentAlignment {
        V_TOP,
        V_CENTER,
        V_BOTTOM,
        H_LEFT,
        H_CENTER,
        H_RIGHT,
    }
}

elk_enum! {
    pub enum Direction {
        UNDEFINED,
        RIGHT,
        LEFT,
        DOWN,
        UP,
    }
}

elk_enum! {
    pub enum EdgeCoords {
        INHERIT,
        CONTAINER,
        PARENT,
        ROOT,
    }
}

elk_enum! {
    pub enum EdgeLabelPlacement {
        CENTER,
        HEAD,
        TAIL,
    }
}

elk_enum! {
    pub enum EdgeRouting {
        UNDEFINED,
        POLYLINE,
        ORTHOGONAL,
        SPLINES,
    }
}

elk_enum! {
    pub enum EdgeType {
        NONE,
        DIRECTED,
        UNDIRECTED,
        ASSOCIATION,
        GENERALIZATION,
        DEPENDENCY,
    }
}

elk_enum! {
    pub enum HierarchyHandling {
        INHERIT,
        INCLUDE_CHILDREN,
        SEPARATE_CHILDREN,
    }
}

elk_enum! {
    pub enum NodeLabelPlacement {
        H_LEFT,
        H_CENTER,
        H_RIGHT,
        V_TOP,
        V_CENTER,
        V_BOTTOM,
        INSIDE,
        OUTSIDE,
        H_PRIORITY,
    }
}

elk_enum! {
    pub enum PortAlignment {
        DISTRIBUTED,
        JUSTIFIED,
        BEGIN,
        CENTER,
        END,
    }
}

elk_enum! {
    pub enum PortConstraints {
        UNDEFINED,
        FREE,
        FIXED_SIDE,
        FIXED_ORDER,
        FIXED_RATIO,
        FIXED_POS,
    }
}

elk_enum! {
    pub enum PortLabelPlacement {
        OUTSIDE,
        INSIDE,
        NEXT_TO_PORT_IF_POSSIBLE,
        ALWAYS_SAME_SIDE,
        ALWAYS_OTHER_SAME_SIDE,
        SPACE_EFFICIENT,
    }
}

elk_enum! {
    pub enum PortSide {
        UNDEFINED,
        NORTH,
        EAST,
        SOUTH,
        WEST,
    }
}

elk_enum! {
    pub enum ShapeCoords {
        INHERIT,
        PARENT,
        ROOT,
    }
}

elk_enum! {
    pub enum SizeConstraint {
        PORTS,
        PORT_LABELS,
        NODE_LABELS,
        MINIMUM_SIZE,
    }
}

elk_enum! {
    pub enum SizeOptions {
        DEFAULT_MINIMUM_SIZE,
        MINIMUM_SIZE_ACCOUNTS_FOR_PADDING,
        COMPUTE_PADDING,
        OUTSIDE_NODE_LABELS_OVERHANG,
        PORTS_OVERHANG,
        UNIFORM_PORT_SPACING,
        SPACE_EFFICIENT_PORT_LABELS,
        FORCE_TABULAR_NODE_LABELS,
        ASYMMETRICAL,
    }
}

elk_enum! {
    pub enum TopdownNodeTypes {
        PARALLEL_NODE,
        HIERARCHICAL_NODE,
        ROOT_NODE,
    }
}

elk_enum! {
    pub enum PackingMode {
        SIMPLE,
        GROUP_DEC,
        GROUP_MIXED,
        GROUP_INC,
    }
}

pub static ALGORITHM: Property<String> = Property::new("org.eclipse.elk.algorithm");
pub static ALIGNMENT: Property<Alignment> = Property::with_default("org.eclipse.elk.alignment", || Alignment::AUTOMATIC);
pub static ASPECT_RATIO: Property<f64> = Property::new("org.eclipse.elk.aspectRatio");
pub static BEND_POINTS: Property<KVectorChain> = Property::new("org.eclipse.elk.bendPoints");
pub static CONTENT_ALIGNMENT: Property<EnumSet<ContentAlignment>> = Property::with_default("org.eclipse.elk.contentAlignment", || EnumSet::of(&[ContentAlignment::V_TOP, ContentAlignment::H_LEFT]));
pub static DEBUG_MODE: Property<bool> = Property::with_default("org.eclipse.elk.debugMode", || false);
pub static DIRECTION: Property<Direction> = Property::with_default("org.eclipse.elk.direction", || Direction::UNDEFINED);
pub static EDGE_ROUTING: Property<EdgeRouting> = Property::with_default("org.eclipse.elk.edgeRouting", || EdgeRouting::UNDEFINED);
pub static EXPAND_NODES: Property<bool> = Property::with_default("org.eclipse.elk.expandNodes", || false);
pub static HIERARCHY_HANDLING: Property<HierarchyHandling> = Property::with_default("org.eclipse.elk.hierarchyHandling", || HierarchyHandling::INHERIT);
pub static PADDING: Property<ElkPadding> = Property::with_default("org.eclipse.elk.padding", || Spacing::uniform(12.0f64));
pub static INTERACTIVE: Property<bool> = Property::with_default("org.eclipse.elk.interactive", || false);
pub static INTERACTIVE_LAYOUT: Property<bool> = Property::with_default("org.eclipse.elk.interactiveLayout", || false);
pub static OMIT_NODE_MICRO_LAYOUT: Property<bool> = Property::with_default("org.eclipse.elk.omitNodeMicroLayout", || false);
pub static PORT_CONSTRAINTS: Property<PortConstraints> = Property::with_default("org.eclipse.elk.portConstraints", || PortConstraints::UNDEFINED);
pub static POSITION: Property<KVector> = Property::new("org.eclipse.elk.position");
pub static PRIORITY: Property<i32> = Property::new("org.eclipse.elk.priority");
pub static RANDOM_SEED: Property<i32> = Property::new("org.eclipse.elk.randomSeed");
pub static SEPARATE_CONNECTED_COMPONENTS: Property<bool> = Property::new("org.eclipse.elk.separateConnectedComponents");
pub static JUNCTION_POINTS: Property<KVectorChain> = Property::with_default("org.eclipse.elk.junctionPoints", || KVectorChain::new());
pub static COMMENT_BOX: Property<bool> = Property::with_default("org.eclipse.elk.commentBox", || false);
pub static HYPERNODE: Property<bool> = Property::with_default("org.eclipse.elk.hypernode", || false);
pub static SOFTWRAPPING_FUZZINESS: Property<f64> = Property::with_default("org.eclipse.elk.softwrappingFuzziness", || 0.0);
pub static MARGINS: Property<ElkMargin> = Property::with_default("org.eclipse.elk.margins", || Spacing::default());
pub static NO_LAYOUT: Property<bool> = Property::with_default("org.eclipse.elk.noLayout", || false);
pub static SCALE_FACTOR: Property<f64> = Property::with_default("org.eclipse.elk.scaleFactor", || 1.0);
pub static CHILD_AREA_WIDTH: Property<f64> = Property::new("org.eclipse.elk.childAreaWidth");
pub static CHILD_AREA_HEIGHT: Property<f64> = Property::new("org.eclipse.elk.childAreaHeight");
pub static TOPDOWN_LAYOUT: Property<bool> = Property::with_default("org.eclipse.elk.topdownLayout", || false);
pub static ANIMATE: Property<bool> = Property::with_default("org.eclipse.elk.animate", || true);
pub static ANIM_TIME_FACTOR: Property<i32> = Property::with_default("org.eclipse.elk.animTimeFactor", || 100);
pub static LAYOUT_ANCESTORS: Property<bool> = Property::with_default("org.eclipse.elk.layoutAncestors", || false);
pub static MAX_ANIM_TIME: Property<i32> = Property::with_default("org.eclipse.elk.maxAnimTime", || 4000);
pub static MIN_ANIM_TIME: Property<i32> = Property::with_default("org.eclipse.elk.minAnimTime", || 400);
pub static PROGRESS_BAR: Property<bool> = Property::with_default("org.eclipse.elk.progressBar", || false);
pub static VALIDATE_GRAPH: Property<bool> = Property::with_default("org.eclipse.elk.validateGraph", || false);
pub static VALIDATE_OPTIONS: Property<bool> = Property::with_default("org.eclipse.elk.validateOptions", || true);
pub static ZOOM_TO_FIT: Property<bool> = Property::with_default("org.eclipse.elk.zoomToFit", || false);
pub static BOX_PACKING_MODE: Property<PackingMode> = Property::with_default("org.eclipse.elk.box.packingMode", || PackingMode::SIMPLE);
pub static JSON_SHAPE_COORDS: Property<ShapeCoords> = Property::with_default("org.eclipse.elk.json.shapeCoords", || ShapeCoords::INHERIT);
pub static JSON_EDGE_COORDS: Property<EdgeCoords> = Property::with_default("org.eclipse.elk.json.edgeCoords", || EdgeCoords::INHERIT);
pub static SPACING_COMMENT_COMMENT: Property<f64> = Property::with_default("org.eclipse.elk.spacing.commentComment", || 10.0);
pub static SPACING_COMMENT_NODE: Property<f64> = Property::with_default("org.eclipse.elk.spacing.commentNode", || 10.0);
pub static SPACING_COMPONENT_COMPONENT: Property<f64> = Property::with_default("org.eclipse.elk.spacing.componentComponent", || 20.0);
pub static SPACING_EDGE_EDGE: Property<f64> = Property::with_default("org.eclipse.elk.spacing.edgeEdge", || 10.0);
pub static SPACING_EDGE_LABEL: Property<f64> = Property::with_default("org.eclipse.elk.spacing.edgeLabel", || 2.0);
pub static SPACING_EDGE_NODE: Property<f64> = Property::with_default("org.eclipse.elk.spacing.edgeNode", || 10.0);
pub static SPACING_LABEL_LABEL: Property<f64> = Property::with_default("org.eclipse.elk.spacing.labelLabel", || 0.0);
pub static SPACING_LABEL_NODE: Property<f64> = Property::with_default("org.eclipse.elk.spacing.labelNode", || 5.0);
pub static SPACING_LABEL_PORT_HORIZONTAL: Property<f64> = Property::with_default("org.eclipse.elk.spacing.labelPortHorizontal", || 1.0);
pub static SPACING_LABEL_PORT_VERTICAL: Property<f64> = Property::with_default("org.eclipse.elk.spacing.labelPortVertical", || 1.0);
pub static SPACING_NODE_NODE: Property<f64> = Property::with_default("org.eclipse.elk.spacing.nodeNode", || 20.0);
pub static SPACING_NODE_SELF_LOOP: Property<f64> = Property::with_default("org.eclipse.elk.spacing.nodeSelfLoop", || 10.0);
pub static SPACING_PORT_PORT: Property<f64> = Property::with_default("org.eclipse.elk.spacing.portPort", || 10.0);
pub static SPACING_INDIVIDUAL: Property<IndividualSpacings> = Property::new("org.eclipse.elk.spacing.individual");
pub static SPACING_PORTS_SURROUNDING: Property<ElkMargin> = Property::with_default("org.eclipse.elk.spacing.portsSurrounding", || Spacing::uniform(0.0f64));
pub static PARTITIONING_PARTITION: Property<i32> = Property::new("org.eclipse.elk.partitioning.partition");
pub static PARTITIONING_ACTIVATE: Property<bool> = Property::with_default("org.eclipse.elk.partitioning.activate", || false);
pub static NODE_LABELS_PADDING: Property<ElkPadding> = Property::with_default("org.eclipse.elk.nodeLabels.padding", || Spacing::uniform(5.0f64));
pub static NODE_LABELS_PLACEMENT: Property<EnumSet<NodeLabelPlacement>> = Property::with_default("org.eclipse.elk.nodeLabels.placement", || EnumSet::none());
pub static PORT_ALIGNMENT_DEFAULT: Property<PortAlignment> = Property::with_default("org.eclipse.elk.portAlignment.default", || PortAlignment::DISTRIBUTED);
pub static PORT_ALIGNMENT_NORTH: Property<PortAlignment> = Property::new("org.eclipse.elk.portAlignment.north");
pub static PORT_ALIGNMENT_SOUTH: Property<PortAlignment> = Property::new("org.eclipse.elk.portAlignment.south");
pub static PORT_ALIGNMENT_WEST: Property<PortAlignment> = Property::new("org.eclipse.elk.portAlignment.west");
pub static PORT_ALIGNMENT_EAST: Property<PortAlignment> = Property::new("org.eclipse.elk.portAlignment.east");
pub static NODE_SIZE_CONSTRAINTS: Property<EnumSet<SizeConstraint>> = Property::with_default("org.eclipse.elk.nodeSize.constraints", || EnumSet::none());
pub static NODE_SIZE_OPTIONS: Property<EnumSet<SizeOptions>> = Property::with_default("org.eclipse.elk.nodeSize.options", || EnumSet::of(&[SizeOptions::DEFAULT_MINIMUM_SIZE]));
pub static NODE_SIZE_MINIMUM: Property<KVector> = Property::with_default("org.eclipse.elk.nodeSize.minimum", || KVector::new(0.0f64, 0.0f64));
pub static NODE_SIZE_FIXED_GRAPH_SIZE: Property<bool> = Property::with_default("org.eclipse.elk.nodeSize.fixedGraphSize", || false);
pub static EDGE_LABELS_PLACEMENT: Property<EdgeLabelPlacement> = Property::with_default("org.eclipse.elk.edgeLabels.placement", || EdgeLabelPlacement::CENTER);
pub static EDGE_LABELS_INLINE: Property<bool> = Property::with_default("org.eclipse.elk.edgeLabels.inline", || false);
pub static FONT_NAME: Property<String> = Property::new("org.eclipse.elk.font.name");
pub static FONT_SIZE: Property<i32> = Property::new("org.eclipse.elk.font.size");
pub static PORT_ANCHOR: Property<KVector> = Property::new("org.eclipse.elk.port.anchor");
pub static PORT_INDEX: Property<i32> = Property::new("org.eclipse.elk.port.index");
pub static PORT_SIDE: Property<PortSide> = Property::with_default("org.eclipse.elk.port.side", || PortSide::UNDEFINED);
pub static PORT_BORDER_OFFSET: Property<f64> = Property::new("org.eclipse.elk.port.borderOffset");
pub static PORT_LABELS_PLACEMENT: Property<EnumSet<PortLabelPlacement>> = Property::with_default("org.eclipse.elk.portLabels.placement", || EnumSet::of(&[PortLabelPlacement::OUTSIDE]));
pub static PORT_LABELS_NEXT_TO_PORT_IF_POSSIBLE: Property<bool> = Property::with_default("org.eclipse.elk.portLabels.nextToPortIfPossible", || false);
pub static PORT_LABELS_TREAT_AS_GROUP: Property<bool> = Property::with_default("org.eclipse.elk.portLabels.treatAsGroup", || true);
pub static TOPDOWN_SIZE_CATEGORIES: Property<i32> = Property::with_default("org.eclipse.elk.topdown.sizeCategories", || 3);
pub static TOPDOWN_SIZE_CATEGORIES_HIERARCHICAL_NODE_WEIGHT: Property<i32> = Property::with_default("org.eclipse.elk.topdown.sizeCategoriesHierarchicalNodeWeight", || 4);
pub static TOPDOWN_SCALE_FACTOR: Property<f64> = Property::with_default("org.eclipse.elk.topdown.scaleFactor", || 1.0);
pub static TOPDOWN_HIERARCHICAL_NODE_WIDTH: Property<f64> = Property::with_default("org.eclipse.elk.topdown.hierarchicalNodeWidth", || 150.0);
pub static TOPDOWN_HIERARCHICAL_NODE_ASPECT_RATIO: Property<f64> = Property::with_default("org.eclipse.elk.topdown.hierarchicalNodeAspectRatio", || 1.414);
pub static TOPDOWN_NODE_TYPE: Property<TopdownNodeTypes> = Property::new("org.eclipse.elk.topdown.nodeType");
pub static TOPDOWN_SCALE_CAP: Property<f64> = Property::with_default("org.eclipse.elk.topdown.scaleCap", || 1.0);
pub static INSIDE_SELF_LOOPS_ACTIVATE: Property<bool> = Property::with_default("org.eclipse.elk.insideSelfLoops.activate", || false);
pub static INSIDE_SELF_LOOPS_YO: Property<bool> = Property::with_default("org.eclipse.elk.insideSelfLoops.yo", || false);
pub static EDGE_THICKNESS: Property<f64> = Property::with_default("org.eclipse.elk.edge.thickness", || 1.0);
pub static EDGE_TYPE: Property<EdgeType> = Property::with_default("org.eclipse.elk.edge.type", || EdgeType::NONE);


pub fn register_core_options(reg: &mut LayoutMetaDataRegistry) {
    reg.register_option(OptionData { id: "org.eclipse.elk.algorithm", group: "", kind: OptionKind::Str, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.resolvedAlgorithm", group: "", kind: OptionKind::Unparseable, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.alignment", group: "", kind: OptionKind::Enum(parse_enum::<Alignment>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.aspectRatio", group: "", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.bendPoints", group: "", kind: OptionKind::Object(parse_kvectorchain), targets: Targets::EDGES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.contentAlignment", group: "", kind: OptionKind::EnumSet(parse_enumset::<ContentAlignment>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.debugMode", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.direction", group: "", kind: OptionKind::Enum(parse_enum::<Direction>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.edgeRouting", group: "", kind: OptionKind::Enum(parse_enum::<EdgeRouting>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.expandNodes", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.hierarchyHandling", group: "", kind: OptionKind::Enum(parse_enum::<HierarchyHandling>), targets: Targets::PARENTS | Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.padding", group: "", kind: OptionKind::Object(parse_padding), targets: Targets::PARENTS | Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.interactive", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.interactiveLayout", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.omitNodeMicroLayout", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.portConstraints", group: "", kind: OptionKind::Enum(parse_enum::<PortConstraints>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.position", group: "", kind: OptionKind::Object(parse_kvector), targets: Targets::NODES | Targets::PORTS | Targets::LABELS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.priority", group: "", kind: OptionKind::Int, targets: Targets::NODES | Targets::EDGES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.randomSeed", group: "", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.separateConnectedComponents", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.junctionPoints", group: "", kind: OptionKind::Object(parse_kvectorchain), targets: Targets::EDGES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.commentBox", group: "", kind: OptionKind::Bool, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.hypernode", group: "", kind: OptionKind::Bool, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.labelManager", group: "", kind: OptionKind::Unparseable, targets: Targets::PARENTS | Targets::LABELS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.softwrappingFuzziness", group: "", kind: OptionKind::Double, targets: Targets::LABELS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.margins", group: "", kind: OptionKind::Object(parse_margin), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.noLayout", group: "", kind: OptionKind::Bool, targets: Targets::NODES | Targets::EDGES | Targets::PORTS | Targets::LABELS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.scaleFactor", group: "", kind: OptionKind::Double, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.childAreaWidth", group: "", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.childAreaHeight", group: "", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.topdownLayout", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.animate", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.animTimeFactor", group: "", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.layoutAncestors", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.maxAnimTime", group: "", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.minAnimTime", group: "", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.progressBar", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.validateGraph", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.validateOptions", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.zoomToFit", group: "", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.box.packingMode", group: "box", kind: OptionKind::Enum(parse_enum::<PackingMode>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.json.shapeCoords", group: "json", kind: OptionKind::Enum(parse_enum::<ShapeCoords>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.json.edgeCoords", group: "json", kind: OptionKind::Enum(parse_enum::<EdgeCoords>), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.commentComment", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.commentNode", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.componentComponent", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.edgeEdge", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.edgeLabel", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.edgeNode", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.labelLabel", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.labelNode", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.labelPortHorizontal", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.labelPortVertical", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.nodeNode", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.nodeSelfLoop", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.portPort", group: "spacing", kind: OptionKind::Double, targets: Targets::PARENTS | Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.individual", group: "spacing", kind: OptionKind::Object(parse_individual_spacings), targets: Targets::NODES | Targets::EDGES | Targets::PORTS | Targets::LABELS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.spacing.portsSurrounding", group: "spacing", kind: OptionKind::Object(parse_margin), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.partitioning.partition", group: "partitioning", kind: OptionKind::Int, targets: Targets::PARENTS | Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.partitioning.activate", group: "partitioning", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.nodeLabels.padding", group: "nodeLabels", kind: OptionKind::Object(parse_padding), targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.nodeLabels.placement", group: "nodeLabels", kind: OptionKind::EnumSet(parse_enumset::<NodeLabelPlacement>), targets: Targets::NODES | Targets::LABELS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.portAlignment.default", group: "portAlignment", kind: OptionKind::Enum(parse_enum::<PortAlignment>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.portAlignment.north", group: "portAlignment", kind: OptionKind::Enum(parse_enum::<PortAlignment>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.portAlignment.south", group: "portAlignment", kind: OptionKind::Enum(parse_enum::<PortAlignment>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.portAlignment.west", group: "portAlignment", kind: OptionKind::Enum(parse_enum::<PortAlignment>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.portAlignment.east", group: "portAlignment", kind: OptionKind::Enum(parse_enum::<PortAlignment>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.nodeSize.constraints", group: "nodeSize", kind: OptionKind::EnumSet(parse_enumset::<SizeConstraint>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.nodeSize.options", group: "nodeSize", kind: OptionKind::EnumSet(parse_enumset::<SizeOptions>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.nodeSize.minimum", group: "nodeSize", kind: OptionKind::Object(parse_kvector), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.nodeSize.fixedGraphSize", group: "nodeSize", kind: OptionKind::Bool, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.edgeLabels.placement", group: "edgeLabels", kind: OptionKind::Enum(parse_enum::<EdgeLabelPlacement>), targets: Targets::LABELS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.edgeLabels.inline", group: "edgeLabels", kind: OptionKind::Bool, targets: Targets::LABELS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.font.name", group: "font", kind: OptionKind::Str, targets: Targets::LABELS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.font.size", group: "font", kind: OptionKind::Int, targets: Targets::LABELS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.port.anchor", group: "port", kind: OptionKind::Object(parse_kvector), targets: Targets::PORTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.port.index", group: "port", kind: OptionKind::Int, targets: Targets::PORTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.port.side", group: "port", kind: OptionKind::Enum(parse_enum::<PortSide>), targets: Targets::PORTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.port.borderOffset", group: "port", kind: OptionKind::Double, targets: Targets::PORTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.portLabels.placement", group: "portLabels", kind: OptionKind::EnumSet(parse_enumset::<PortLabelPlacement>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.portLabels.nextToPortIfPossible", group: "portLabels", kind: OptionKind::Bool, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.portLabels.treatAsGroup", group: "portLabels", kind: OptionKind::Bool, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.topdown.sizeCategories", group: "topdown", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.topdown.sizeCategoriesHierarchicalNodeWeight", group: "topdown", kind: OptionKind::Int, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.topdown.scaleFactor", group: "topdown", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.topdown.sizeApproximator", group: "topdown", kind: OptionKind::Unparseable, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.topdown.hierarchicalNodeWidth", group: "topdown", kind: OptionKind::Double, targets: Targets::PARENTS | Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.topdown.hierarchicalNodeAspectRatio", group: "topdown", kind: OptionKind::Double, targets: Targets::PARENTS | Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.topdown.nodeType", group: "topdown", kind: OptionKind::Enum(parse_enum::<TopdownNodeTypes>), targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.topdown.scaleCap", group: "topdown", kind: OptionKind::Double, targets: Targets::PARENTS, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.insideSelfLoops.activate", group: "insideSelfLoops", kind: OptionKind::Bool, targets: Targets::NODES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.insideSelfLoops.yo", group: "insideSelfLoops", kind: OptionKind::Bool, targets: Targets::EDGES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.edge.thickness", group: "edge", kind: OptionKind::Double, targets: Targets::EDGES, legacy_ids: &[] });
    reg.register_option(OptionData { id: "org.eclipse.elk.edge.type", group: "edge", kind: OptionKind::Enum(parse_enum::<EdgeType>), targets: Targets::EDGES, legacy_ids: &[] });
}

// Skipped internal/unsupported-type properties:
//   RESOLVED_ALGORITHM: LayoutAlgorithmData
//   LABEL_MANAGER: ILabelManager
//   TOPDOWN_SIZE_APPROXIMATOR: ITopdownSizeApproximator
